batch_method: binary_link_neighbors
batch_norm: true
batch_size: 128
book_features:
- degree_log_transform: true
  features:
  - degree
  - coreness
  name: topo
- name: textual_desc
- aggr_fn: mean
  name: textual_reviews
books_filename: books_filtered.parquet
coreness_k: 10
decoder: inner_product_decoder
descriptions_filename: descriptions_filtered.parquet
dir: ../data_sample
disjoint_train_ratio: 0.0
dropout: 0.3
edge_type: reads
embeddings_descriptions_filename: embeddings_descriptions_sbert_pt.parquet
embeddings_reviews_filename: embeddings_reviews_sbert_pt.parquet
encoder: sage_encoder
epochs: 1
eval_interval: 1
feature_aggr_method: concat
feature_linear_dim: 128
hidden_channels: 128
interactions_filename: interactions.parquet
item_emb_dim: 128
item_feature_linear: true
kl_beta: 0.2
kl_warmup_epoch: 30
language_filter: true
latent_dim: 64
learning_rate: 0.001
n_layer: 1
negative_sampling_method: pairwise_random
negative_sampling_ratio: 30.0
negative_sampling_recurrence: epoch
num_neighbors:
- 10
- 10
opt_decay_rate: 0.1
opt_decay_step: 20
patience: 50
recon_loss: bpr
retrieval_k: 300
review_coreness_k: 5
reviews_filename: reviews_filtered.parquet
save_model: false
seed: 42
skip_connection: sum
test_size: 0.2
tsne_visualization: false
user_emb_dim: 128
user_feature_linear: true
user_features:
- degree_log_transform: true
  features:
  - degree
  - coreness
  name: topo
- aggr_fn: mean
  name: textual_reviews
users_filename: users_filtered.parquet
val_size: 0.2
variational: true
weight_decay: 1.0e-05
